/* Generated by tools/gen_ecg_filters.py - do not edit by hand.
 *
 * The filter structure is power-of-two leaky integrators and boxcar moving
 * averages only. See the script's docstring for why biquads were abandoned.
 * Every "measured" figure below is |H(f)| of this exact integer structure
 * evaluated on the unit circle at fs = 1000 Hz. */

#ifndef ECG_FILTER_COEFF_H
#define ECG_FILTER_COEFF_H

#define ECG_FILTER_DESIGN_FS   1000UL   /* every number here assumes this */

/* ---- display path ------------------------------------------------------- */
/* Baseline high-pass: two cascaded leaky integrators, pole period 2^8
 * samples. Measured: -4.1 dB at 0.5 Hz, -1.4 dB at 1 Hz, so wander
 * below ~1 Hz is rejected while a QRS is preserved. */
#define ECG_BASELINE_SHIFT_K        8U
#define ECG_BASELINE_INPUT_Q        8U
#define ECG_BASELINE_CORNER_HZ      0.62f   /* per pole, measured */

/* Mains comb. A boxcar of N taps has an exact null at FS/N, so N=20 nulls
 * 50 Hz outright - measured -313.4 dB at 50 Hz and -322.9 dB at 100 Hz.
 * The same section is the display low-pass; as a cascade with the 0.62 Hz
 * high-pass above it measures -3 dB at 22.1 Hz, and on its own it
 * measures 22.2 Hz. Both are quoted because they are different
 * questions about the same 20 taps. */
#define ECG_COMB_TAPS_50HZ          20U
#define ECG_COMB_50HZ_M3DB_HZ       22.1f
#define ECG_COMB_50HZ_NULL_HZ       50.0f

/* 60 Hz variant. 1000/60 is not an integer, so no boxcar can null 60 Hz
 * exactly; the nearest is N=17, which nulls at 58.8 Hz and leaves
 * -34.1 dB at 60 Hz. Its own -3 dB corner is 26.1 Hz. Documented
 * rather than hidden: a true 60 Hz null would need a fractional delay or an IIR
 * section. */
#define ECG_COMB_TAPS_60HZ          17U
#define ECG_COMB_60HZ_NULL_HZ       58.8f
#define ECG_COMB_60HZ_AT_60_DB      -34.1f

/* ---- QRS detection path ------------------------------------------------- */
/* High-pass, single leaky pole: fc = FS/(2*pi*2**5) = 4.97 Hz;
 * measured -3 dB rising at 5.22 Hz. */
#define ECG_QRS_HP_SHIFT            5U

/* Low-pass: one boxcar of 20 taps averaged by an exact divide, so the 50 Hz
 * null is exact rather than approached. Same 20 taps as the display comb, so
 * the same -3 dB corner: 22.2 Hz, and -313.6 dB at 50 Hz. */
#define ECG_QRS_LP_TAPS             20U
#define ECG_QRS_LP_M3DB_HZ          22.2f
#define ECG_MA20_M3DB_HZ            22.2f   /* shared by both 20-tap sections */

/* The cascade of the two sections above, which is what the detector actually
 * sees. It is a band-pass: its |H| peaks at 11.2 Hz, -1.7 dB
 * below unity, and the -3 dB points relative to that peak are
 * 3.8 Hz to 26.3 Hz. At 44 Hz it is already down
 * -17.7 dB, so this is NOT a 5-44 Hz band; earlier text here said so and was
 * derived from measuring the cascade against its own gain at 1 Hz, which sits in
 * the high-pass stop band. Points -3.3 dB down at 5 Hz and -4.2 dB at
 * 25 Hz, so energy near the QRS dominates mains-free content above ~26 Hz. */
#define ECG_QRS_BAND_LO_HZ          3.8f
#define ECG_QRS_BAND_HI_HZ          26.3f
#define ECG_QRS_PEAK_HZ             11.2f

/* Moving-window integrator over the squared derivative, 120 samples = 120 ms.
 * Its first spectral null sits at 8.3 Hz. */
#define ECG_MWI_WINDOW_SAMPLES      120U

/* Largest tap count any boxcar stage needs; sizes the shared ring storage. */
#define ECG_BOX_MAX_TAPS            20U

#endif /* ECG_FILTER_COEFF_H */
