/* Generated by tools/gen_ecg_filters.py - do not edit by hand.
 * Every 'measured' comment is the response of the QUANTISED coefficients
 * evaluated at the design sample rate 1000 Hz. Where it differs from the
 * nominal cutoff, the measured number is the truth.
 * The display high-pass is absent on purpose: 0.5 Hz is not representable
 * as a Q14 biquad at 1 kHz, so it uses cascaded leaky integrators. */

#ifndef ECG_FILTER_COEFF_H
#define ECG_FILTER_COEFF_H

#define ECG_FILTER_Q_FORMAT   14
#define ECG_FILTER_Q_SCALE    (1 << 14)
#define ECG_FILTER_DESIGN_FS  1000UL /* pipeline is invalid at another fs */

/* Display path low-pass, nominal 40 Hz Q=0.7071
 * measured -3 dB: 43.29 Hz
 */
#define ECG_F_LP40_B0      219 /* +0.013359200 */
#define ECG_F_LP40_B1      515 /* +0.031416839 */
#define ECG_F_LP40_B2      219 /* +0.013359200 */
#define ECG_F_LP40_A1   -26992 /* -1.647459981 */
#define ECG_F_LP40_A2    11483 /* +0.700896781 */

/* QRS path high-pass, nominal 5 Hz Q=0.7071
 * measured -3 dB: 5.00 Hz
 */
#define ECG_F_HP5_B0    16024 /* +0.978030479 */
#define ECG_F_HP5_B1   -32048 /* -1.956060958 */
#define ECG_F_HP5_B2    16024 /* +0.978030479 */
#define ECG_F_HP5_A1   -32040 /* -1.955578240 */
#define ECG_F_HP5_A2    15672 /* +0.956543677 */

/* QRS path low-pass, nominal 15 Hz Q=0.7071
 * measured -3 dB: 15.50 Hz
 */
#define ECG_F_LP15_B0       34 /* +0.002080567 */
#define ECG_F_LP15_B1       73 /* +0.004438035 */
#define ECG_F_LP15_B2       34 /* +0.002080567 */
#define ECG_F_LP15_A1   -30587 /* -1.866892280 */
#define ECG_F_LP15_A2    14340 /* +0.875214548 */

/* Power-line notch 50 Hz Q=30 (default)
 * gain at 50/10 Hz: -39.4 dB / -0.0 dB
 */
#define ECG_F_N50_B0    16300 /* +0.994876106 */
#define ECG_F_N50_B1   -31005 /* -1.892366808 */
#define ECG_F_N50_B2    16300 /* +0.994876106 */
#define ECG_F_N50_A1   -31005 /* -1.892366808 */
#define ECG_F_N50_A2    16216 /* +0.989752213 */

/* Power-line notch 60 Hz Q=30 (optional)
 * gain at 60/10 Hz: -65.4 dB / -0.0 dB
 */
#define ECG_F_N60_B0    16284 /* +0.993902004 */
#define ECG_F_N60_B1   -30281 /* -1.848213426 */
#define ECG_F_N60_B2    16284 /* +0.993902004 */
#define ECG_F_N60_A1   -30281 /* -1.848213426 */
#define ECG_F_N60_A2    16184 /* +0.987804009 */

#endif /* ECG_FILTER_COEFF_H */
