"""Cross-language parity: replay frames produced by the firmware's own C encoder.

``tests/host/protocol_vectors.json`` is generated by
``tools/gen_protocol_vectors.py``, which compiles ``tests/host/dump_vectors.c``
against the real ``App/protocol/crc16.c`` and ``protocol.c`` -- the same objects
that link into the firmware. Nothing in this file is hand-written, so a change to
either implementation that moves a byte fails here rather than on a bench.

The typed vectors carry distinguishable values on purpose: a wrong field offset
shows up as a wrong number, not as a lucky zero.
"""
from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

from pc_monitor import protocol as p

REPO = Path(__file__).resolve().parents[2]
VECTOR_FILE = REPO / "tests" / "host" / "protocol_vectors.json"


def _load() -> dict[str, str]:
    doc = json.loads(VECTOR_FILE.read_text(encoding="utf-8"))
    return doc["vectors"]


VECTORS = _load()
# Emitted as hex strings without a frame around them.
SCALARS = {"protocol_version", "crc16_check"}
FRAME_NAMES = sorted(set(VECTORS) - SCALARS)


def payload_of(name: str) -> bytes:
    result, frame, consumed = p.parse_frame(bytes.fromhex(VECTORS[name]))
    assert result is p.ParseResult.OK, "%s did not parse: %r" % (name, result)
    assert consumed == len(VECTORS[name]) // 2
    return frame.payload


class TestVectorFileIsUsable:
    def test_the_file_exists_and_is_not_empty(self):
        assert VECTOR_FILE.is_file(), "run tools/gen_protocol_vectors.py"
        assert len(FRAME_NAMES) >= 15

    @pytest.mark.skipif(importlib.util.find_spec("ziglang") is None,
                        reason="needs the ziglang C toolchain (pip install ziglang)")
    def test_regenerating_reproduces_the_committed_file(self):
        """The JSON is a build product, so a stale one has to be loud.

        Without this the parity tests would keep passing against an old snapshot
        forever, which is exactly the drift they exist to detect.
        """
        import subprocess
        import sys

        proc = subprocess.run(
            [sys.executable, str(REPO / "tools" / "gen_protocol_vectors.py")],
            capture_output=True, text=True,
        )
        assert proc.returncode == 0, proc.stdout + proc.stderr
        assert _load() == VECTORS, (
            "protocol_vectors.json is stale; commit the regenerated file"
        )


class TestCrcParity:
    def test_the_c_crc_matches_the_python_crc_on_the_check_vector(self):
        assert int(VECTORS["crc16_check"], 16) == p.CRC16_CHECK == 0x29B1

    def test_both_sides_declare_the_same_protocol_version(self):
        assert int(VECTORS["protocol_version"], 16) == p.PROTOCOL_VERSION

    @pytest.mark.parametrize("name", FRAME_NAMES)
    def test_c_frames_verify_under_the_python_crc(self, name):
        raw = bytes.fromhex(VECTORS[name])
        assert p.crc16_ccitt(raw[:-2]) == int.from_bytes(raw[-2:], "little")


class TestFrameParity:
    @pytest.mark.parametrize("name", FRAME_NAMES)
    def test_python_reencodes_the_c_frame_byte_for_byte(self, name):
        raw = bytes.fromhex(VECTORS[name])
        _, frame, _ = p.parse_frame(raw)
        again = p.encode_frame(frame.type, frame.sequence, frame.device_ts_ms,
                               frame.payload)
        assert again == raw, "%s re-encodes differently" % name

    @pytest.mark.parametrize("n", range(0, 9))
    def test_the_declared_payload_length_is_what_the_c_encoder_used(self, n):
        _, frame, _ = p.parse_frame(bytes.fromhex(VECTORS["sized_%d" % n]))
        assert frame.length == n == len(frame.payload)
        assert frame.type == int(p.PacketType.PONG)
        assert frame.device_ts_ms == 0xF0F0F0F0


class TestEcgBatchFieldsFromC:
    """The tail that ``send_ecg_batch()`` writes, read back at the Python offsets."""

    def test_a_full_batch_is_69_bytes_on_the_wire(self):
        raw = bytes.fromhex(VECTORS["ecg_batch_typical"])
        assert len(raw) == 69
        _, frame, _ = p.parse_frame(raw)
        assert frame.length == p.ecg_batch_payload_len(p.ECG_BATCH_MAX_SAMPLES) == 55

    @pytest.mark.parametrize("name", [
        "ecg_batch_all_flags", "ecg_batch_typical",
        "ecg_batch_single_sample", "ecg_batch_low_bytes",
    ])
    def test_the_tail_fields_survive(self, name):
        batch = p.decode_ecg_batch(payload_of(name))
        assert batch.temp_raw == 1731
        assert batch.temp_centi == 3667
        assert batch.hr_bpm == 72
        assert batch.hr_state == int(p.HrState.NORMAL)
        assert batch.sample_period_us == p.SAMPLE_PERIOD_US
        assert batch.first_sample_index == 0x1E240
        assert len(batch.samples) == batch.count

    EXPECTED_BATCH_FLAGS = {
        "ecg_batch_all_flags": 0xFFFF,
        "ecg_batch_low_bytes": 0x00FF,
        "ecg_batch_single_sample": 0x0100,
        "ecg_batch_typical": (p.SFLAG_ADC_RUNNING | p.SFLAG_RTC_VALID |
                              p.SFLAG_HR_VALID | int(p.LeadState.SIGNAL_POOR)),
    }

    @pytest.mark.parametrize("name", sorted(EXPECTED_BATCH_FLAGS))
    def test_the_flag_word_arrives_whole(self, name):
        """The regression: a 7-byte ECGP_TAIL silently clipped this to 0x00FF."""
        assert p.decode_ecg_batch(payload_of(name)).flags == self.EXPECTED_BATCH_FLAGS[name]

    def test_the_typical_batch_exercises_every_high_bit(self):
        flags = p.decode_ecg_batch(payload_of("ecg_batch_typical")).flags_decoded
        assert flags.adc_running is True
        assert flags.rtc_valid is True
        assert flags.hr_valid is True
        assert flags.oled_present is False
        assert flags.recording is False
        assert int(flags.lead) == int(p.LeadState.SIGNAL_POOR)

    def test_one_sample_batches_are_legal_too(self):
        batch = p.decode_ecg_batch(payload_of("ecg_batch_single_sample"))
        assert batch.count == 1
        assert len(bytes.fromhex(VECTORS["ecg_batch_single_sample"])) == 14 + 17


class TestTypedPayloadsFromC:
    def test_hello_reports_the_build_it_came_from(self):
        hello = p.decode_hello(payload_of("hello"))
        assert (hello.fw_major, hello.fw_minor, hello.fw_patch) == (1, 0, 0)
        assert hello.proto_version == p.PROTOCOL_VERSION
        assert hello.sample_rate_hz == 1000
        assert hello.batch_max_samples == p.ECG_BATCH_MAX_SAMPLES
        assert hello.adc_bits == 12
        assert hello.caps == 0

    def test_status_offsets_match_field_by_field(self):
        st = p.decode_status(payload_of("status"))
        assert st.adc_running is True
        assert st.dma_blocks == 4660
        assert st.dma_dropped == 0
        assert st.ecg_samples == 100000
        assert st.temp_valid is False
        assert st.temp_centi == 3667
        assert st.hr_bpm == 72
        assert st.hr_state == int(p.HrState.NORMAL)
        assert st.oled_present is False
        assert st.oled_addr == 0
        assert st.rtc_valid is True
        assert st.uart_tx == 500000
        assert st.uart_rx == 1200
        assert st.uart_crc_err == 3
        assert st.proto_err == 1
        assert st.uptime_s == 3600

    def test_status_carries_the_whole_flag_word(self):
        st = p.decode_status(payload_of("status"))
        assert st.flags == 0x5783
        flags = p.split_flags(st.flags)
        assert flags.recording and flags.oled_present
        assert flags.adc_running and flags.rtc_valid
        assert flags.temp_uncalibrated
        assert int(flags.notch) == int(p.NotchMode.HZ60)
        assert int(flags.lead) == int(p.LeadState.SIGNAL_POOR)
        assert st.flags == p.make_flags(
            lead=p.LeadState.SIGNAL_POOR, temp=p.TempState.OK, hr_valid=False,
            recording=True, oled_present=True, adc_running=True, rtc_valid=True,
            dma_dropped=False, notch=p.NotchMode.HZ60, temp_uncalibrated=True)

    def test_temp_status_keeps_uncalibrated_distinct_from_a_number(self):
        ts = p.decode_temp_status(payload_of("temp_status"))
        assert ts.temp_raw == 1234
        assert ts.temp_mv == 1000
        assert ts.temp_centi == 3657
        assert ts.temp_state == int(p.TempState.UNCALIBRATED)
        # A centi value plus an UNCALIBRATED state is exactly the case the UI
        # must not render as a temperature.
        assert p.centi_to_c(ts.temp_centi) == pytest.approx(36.57)

    def test_rtc_response_calendar_and_agreeing_epoch(self):
        cal = p.decode_rtc_response(payload_of("rtc_response"))
        assert (cal.year, cal.month, cal.day) == (2031, 11, 23)
        assert (cal.hour, cal.minute, cal.second) == (6, 45, 12)
        assert cal.epoch == 1953182712

    def test_set_config_rounds_through_the_c_offsets(self):
        """SET_CONFIG is host->device, so it has no inbound dispatcher entry."""
        cfg = p.SetConfig.decode(payload_of("set_config"))
        assert cfg.notch == int(p.NotchMode.HZ50)
        assert (cfg.hr_low, cfg.hr_high) == (45, 130)
        assert (cfg.temp_low_centi, cfg.temp_high_centi) == (3500, 3850)


def _frame(name: str) -> p.Frame:
    _, frame, _ = p.parse_frame(bytes.fromhex(VECTORS[name]))
    return frame


class TestHandWrittenGoldenFrames:
    """Independently computed vectors, so a shared bug cannot agree with itself."""

    def test_every_golden_frame_parses_and_matches_its_declared_fields(self):
        for vector in p.iter_golden():
            result, frame, consumed = p.parse_frame(vector.bytes)
            assert result is p.ParseResult.OK, vector.name
            assert consumed == len(vector.bytes), vector.name
            assert frame.type == vector.type, vector.name
            assert frame.sequence == vector.sequence, vector.name
            assert frame.device_ts_ms == vector.device_ts_ms, vector.name
            assert frame.length == vector.payload_len, vector.name

    def test_the_goldens_all_declare_the_current_protocol_version(self):
        for vector in p.iter_golden():
            assert vector.bytes[2] == p.PROTOCOL_VERSION, vector.name

    def test_the_20_sample_golden_batch_is_the_same_size_as_the_c_one(self):
        golden = p.golden_by_name("ecg_batch_n20_full")
        assert len(golden.bytes) == len(bytes.fromhex(VECTORS["ecg_batch_typical"]))
