#!/usr/bin/env python3
"""
Derive the fixed-point biquad coefficients used by the ECG pipeline and emit
App/config/ecg_filter_coeff.h.

Why a generator instead of hand-typed numbers: every coefficient in the emitted
header is the bilinear transform of an explicit analogue prototype, quantised to
a documented Q format, and then re-measured through the *quantised* filter, so
the header records the response the firmware will actually get rather than the
response that was asked for. Run with the pc_monitor venv interpreter:

    pc_monitor/.venv/Scripts/python.exe tools/gen_ecg_filters.py

and commit the regenerated header together with this script. tests/test_ecg_filters.py
re-derives these numbers and fails if the header drifts from the prototypes.
"""
from __future__ import annotations

import math
from pathlib import Path

FS = 1000.0            # sample rate, Hz - must equal ADC_SAMPLE_RATE_HZ
Q = 14                 # coefficient Q format, signed
SQRT2 = math.sqrt(2.0)


def rpf2_hp(fc: float, q: float = SQRT2 / 2.0):
    """RBJ high-pass, bilinear, unity gain well above fc."""
    w0 = 2.0 * math.pi * fc / FS
    alpha = math.sin(w0) / (2.0 * q)
    cw = math.cos(w0)
    a0 = 1.0 + alpha
    return ([(1.0 + cw) / 2.0 / a0, -(1.0 + cw) / a0, (1.0 + cw) / 2.0 / a0],
            [1.0, -2.0 * cw / a0, (1.0 - alpha) / a0])


def rpf2_lp(fc: float, q: float = SQRT2 / 2.0):
    """RBJ low-pass, unity DC gain."""
    w0 = 2.0 * math.pi * fc / FS
    alpha = math.sin(w0) / (2.0 * q)
    cw = math.cos(w0)
    a0 = 1.0 + alpha
    return ([(1.0 - cw) / 2.0 / a0, 1.0 - cw, (1.0 - cw) / 2.0 / a0],
            [1.0, -2.0 * cw / a0, (1.0 - alpha) / a0])


def rpf2_notch(fc: float, q: float = 30.0):
    """RBJ notch, unity gain away from fc."""
    w0 = 2.0 * math.pi * fc / FS
    alpha = math.sin(w0) / (2.0 * q)
    cw = math.cos(w0)
    a0 = 1.0 + alpha
    return ([1.0 / a0, -2.0 * cw / a0, 1.0 / a0],
            [1.0, -2.0 * cw / a0, (1.0 - alpha) / a0])


def quantise(b, a):
    """(b0,b1,b2,a1,a2) in Q format. a0 normalises to 1.0 == 1 << Q."""
    bq = [round(c * (1 << Q)) for c in b]
    aq = [round(c * (1 << Q)) for c in a]
    assert aq[0] == (1 << Q), f"a0 quantised to {aq[0]}, expected {1 << Q}"
    return bq[0], bq[1], bq[2], aq[1], aq[2]


def response_gain(qb, freq_hz: float) -> float:
    """|H(f)| of the quantised biquad, evaluated on the unit circle.

    Numerator and denominator must be brought to the same scale: b*, a1 and a2
    are all round(coefficient * 2**Q) while the implicit a0 is 1.0 == 1 << Q.
    Scaling only the denominator inflates the result by 2**Q.
    """
    b0, b1, b2, a1, a2 = qb
    w = 2.0 * math.pi * freq_hz / FS
    z = complex(math.cos(w), math.sin(w))
    scale = float(1 << Q)
    num = (b0 + b1 / z + b2 / (z * z)) / scale
    den = 1.0 + (a1 / scale) / z + (a2 / scale) / (z * z)
    return abs(num / den)


def half_power_freq(qb, kind: str, lo=0.05, hi=490.0, tol=0.005) -> float:
    """Binary-search the -3 dB point of a quantised section."""
    target = 1.0 / math.sqrt(2.0)
    for _ in range(400):
        mid = 0.5 * (lo + hi)
        above = response_gain(qb, mid) > target
        if (kind == "lp" and above) or (kind == "hp" and not above):
            lo = mid
        else:
            hi = mid
        if hi - lo < tol:
            break
    return 0.5 * (lo + hi)


def db(v: float) -> str:
    return f"{20 * math.log10(max(v, 1e-12)):.1f} dB"


def main() -> None:
    # The display path's ~0.5 Hz high-pass is deliberately NOT a biquad here.
    # At fs = 1000 Hz a 0.5 Hz pole sits at r = 0.99687, and -2*r*cos(w0) needs
    # more fractional bits than Q14 has: the quantised 0.5 Hz high-pass collapsed
    # to a1 + a2 == -2**14, i.e. a pole exactly on z = 1 and an unbounded DC
    # gain. It is realised structurally instead as cascaded power-of-two leaky
    # integrators (ecg_config.h / ecg_signal.c), which are exact in int32.
    specs = [
        ("LP40", "Display path low-pass, nominal 40 Hz Q=0.7071", rpf2_lp(40.0)),
        ("HP5",  "QRS path high-pass, nominal 5 Hz Q=0.7071",      rpf2_hp(5.0)),
        ("LP15", "QRS path low-pass, nominal 15 Hz Q=0.7071",      rpf2_lp(15.0)),
        ("N50",  "Power-line notch 50 Hz Q=30 (default)",          rpf2_notch(50.0)),
        ("N60",  "Power-line notch 60 Hz Q=30 (optional)",         rpf2_notch(60.0)),
    ]

    lines: list[str] = [
        "/* Generated by tools/gen_ecg_filters.py - do not edit by hand.\n"
        " * Every 'measured' comment is the response of the QUANTISED coefficients\n"
        f" * evaluated at the design sample rate {FS:.0f} Hz. Where it differs from the\n"
        " * nominal cutoff, the measured number is the truth.\n"
        " * The display high-pass is absent on purpose: 0.5 Hz is not representable\n"
        " * as a Q14 biquad at 1 kHz, so it uses cascaded leaky integrators. */\n\n"
        "#ifndef ECG_FILTER_COEFF_H\n#define ECG_FILTER_COEFF_H\n\n",
        f"#define ECG_FILTER_Q_FORMAT   {Q}\n",
        f"#define ECG_FILTER_Q_SCALE    (1 << {Q})\n",
        f"#define ECG_FILTER_DESIGN_FS  {FS:.0f}UL /* pipeline is invalid at another fs */\n\n",
    ]
    summary: list[str] = []

    for name, comment, (b, a) in specs:
        qb = quantise(b, a)
        if name.startswith("LP"):
            probe = ("measured -3 dB", f"{half_power_freq(qb, 'lp'):.2f} Hz")
        elif name.startswith("HP"):
            probe = ("measured -3 dB", f"{half_power_freq(qb, 'hp'):.2f} Hz")
        else:
            centre = 50.0 if name == "N50" else 60.0
            probe = (f"gain at {centre:.0f}/10 Hz",
                     f"{db(response_gain(qb, centre))} / {db(response_gain(qb, 10.0))}")

        lines.append(
            f"/* {comment}\n"
            f" * {probe[0]}: {probe[1]}\n"
            f" */\n"
            f"#define ECG_F_{name}_B0  {qb[0]:>7} /* {b[0]:+.9f} */\n"
            f"#define ECG_F_{name}_B1  {qb[1]:>7} /* {b[1]:+.9f} */\n"
            f"#define ECG_F_{name}_B2  {qb[2]:>7} /* {b[2]:+.9f} */\n"
            f"#define ECG_F_{name}_A1  {qb[3]:>7} /* {a[1]:+.9f} */\n"
            f"#define ECG_F_{name}_A2  {qb[4]:>7} /* {a[2]:+.9f} */\n\n"
        )
        summary.append(f"  {name:5} b=[{qb[0]:6},{qb[1]:6},{qb[2]:6}] "
                       f"a=[{qb[3]:6},{qb[4]:6}]  {probe[0]}={probe[1]}")

    lines.append("#endif /* ECG_FILTER_COEFF_H */\n")

    dest = Path(__file__).resolve().parent.parent / "App" / "config" / "ecg_filter_coeff.h"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("".join(lines), encoding="utf-8", newline="\n")

    print(f"wrote {dest}")
    print("\n".join(summary))


if __name__ == "__main__":
    main()
